export const SET_PERSIST = "SET_PERSIST";
export const GET_PERSIST = "GET_PERSIST";
export const CLEAR_DATAFROM = "CLEAR_DATAFROM";
export const RESET = "RESET";

export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAR_LOGIN_DATAFROM = "CLEAR_LOGIN_DATAFROM";
export const RESET_LOGIN = "RESET_LOGIN";

export const CATEGORIES_RETRIEVED = "CATEGORIES_RETRIEVED";
export const CATEGORIES_FAIL = "CATEGORIES_FAIL";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
export const CLEAR_ADDCAT_DATAFROM = "CLEAR_ADDCAT_DATAFROM";
export const RESET_CATEGORIES = "RESET_CATEGORIES";

export const BUDGETS_RETRIEVED = "BUDGETS_RETRIEVED";
export const BUDGETS_FAIL = "BUDGETS_FAIL";
export const CREATE_BUDGET_SUCCESS = "CREATE_BUDGET_SUCCESS";
export const CREATE_BUDGET_FAIL = "CREATE_BUDGET_FAIL";
export const CLEAR_CREATEBUD_DATAFROM = "CLEAR_CREATEBUD_DATAFROM";
export const RESET_BUDGETS = "RESET_BUDGETS";

export const TRANSACTIONS_RETRIEVED = "TRANSACTIONS_RETRIEVED";
export const TRANSACTIONS_FAIL = "TRANSACTIONS_FAIL";
export const CREATE_TRANS_SUCCESS = "CREATE_TRANS_SUCCESS";
export const CREATE_TRANS_FAIL = "CREATE_TRANS_FAIL";
export const CLEAR_TRANSACTIONS_DATAFROM = "CLEAR_TRANSACTIONS_DATAFROM";
export const RESET_TRANSACTIONS = "RESET_TRANSACTIONS";

export const INCOME_RETRIEVED = "INCOME_RETRIEVED";
export const INCOME_FAIL = "INCOME_FAIL";
export const SET_EXPECTED_SUCCESS = "SET_EXPECTED_SUCCESS";
export const SET_EXPECTED_FAIL = "SET_EXPECTED_FAIL";
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS";
export const ADD_INCOME_FAIL = "ADD_INCOME_FAIL";
export const CLEAR_INCOME_DATAFROM = "CLEAR_INCOME_DATAFROM";
export const RESET_INCOME = "RESET_INCOME";
